name: Deploy Astro to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'astro/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: astro/package-lock.json

      - name: Install dependencies
        working-directory: ./astro
        run: npm ci

      - name: Build Astro site
        working-directory: ./astro
        run: npm run build

      - name: Deploy to docs folder
        run: |
          rm -rf docs/*
          cp -r astro/dist/* docs/
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/
          git diff --staged --quiet || git commit -m "🚀 Deploy Astro build to GitHub Pages"
          git push
